---
- hosts: webservers
  user: ansible
  become: true
  connection: ssh
  tasks:
     - name: Cloning a Git repository
       git:
         repo: https://github.com/Msocial123/Flipkart-Clone.git
         dest: /var/www/html/
         version: main 
         force: yes

     - name: Start and Enable webserver
       service:
        name: httpd
        state: started
        enabled: yes