- hosts: webservers
  user: ansible
  become: yes
  connection: ssh
  tasks:
    - name: Install Openjdk
      yum:
        name: java-17-amazon-corretto.x86_64
        state: present

    - name: Download the Jenkins Repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Import Jenkins GPG Key
      rpm_key:
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
        state: present

    - name: Download EPEL release RPM
      get_url:
        url: http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        dest: /tmp/epel-release-latest-7.noarch.rpm

    - name: Install EPEL release RPM
      yum:
        name: /tmp/epel-release-latest-7.noarch.rpm
        state: present
        disable_gpg_check: true

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Start Jenkins
      service:
        name: jenkins
        state: started

    - name: Enable Jenkins on boot
      systemd:
        name: jenkins
        enabled: true

    - name: Wait for Jenkins to be available
      wait_for:
        delay: 30
        port: 8080

    - name: Get the Jenkins Admin Password
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkinspass

    - name: Print Jenkins Admin Password
      debug:
        var: jenkinspass.stdout